name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test DevopsAssignment.Test/DevopsAssignment.Test.csproj --no-restore --verbosity normal

      - name: Build Docker image
        run: |
          docker build -t trangbachkhoa309/cicdbasic-devopsassignment:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: huynhphuongtrang309@gmail.com
          password: TrangBK309!

      - name: Push Docker image to Docker Hub
        run: |
          docker push trangbachkhoa309/cicdbasic-devopsassignment:latest